import {test,expect} from '@playwright/test';
test.use({browserName:'webkit'});
test('worker highlighting and bottom-right copy remain usable with overflowing code',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as any).copied=text;}}}));
 await page.goto('/tests/code-block.html');
 await expect(page.locator('.token.keyword').first()).toHaveText('def');
 await page.getByRole('button',{name:'Copy code'}).first().click();
 expect(await page.evaluate(()=>(window as any).copied)).toBe('def hello():\n    return "hello"');
 const lean=page.locator('.md-code-block').nth(1);
 await expect(lean.locator('.token.keyword').first()).toHaveText('structure');
 await expect(lean.locator('.token.class-name').first()).toHaveText('UIntN');
 expect(await lean.locator('.token.keyword').first().evaluate(el=>getComputedStyle(el).color)).not.toBe(await lean.locator('code').evaluate(el=>getComputedStyle(el).color));
 const block=page.locator('.md-code-block').last();
 await block.locator('pre').evaluate(el=>{el.scrollLeft=10000;});
 await block.getByRole('button').click();
 expect(await page.evaluate(()=>(window as any).copied)).toContain('last line');
 await expect(page.getByRole('button',{name:'Copy response'})).toBeVisible();
 const rect=await block.boundingBox();
 const copyRect=await block.getByRole('button').boundingBox();
 expect(copyRect!.x).toBeGreaterThan(rect!.x);
 expect(copyRect!.x+copyRect!.width).toBeLessThan(rect!.x+rect!.width);
 expect(copyRect!.y+copyRect!.height).toBeLessThan(rect!.y+rect!.height);
 await page.getByRole('button',{name:'Copy response'}).click();
 expect(await page.evaluate(()=>(window as any).copied)).toContain('```python');
 await page.screenshot({path:'test-results/code-block.png'});
});
