import {test,expect} from '@playwright/test';
test.use({browserName:'webkit'});
test('software inventory is subtle, expandable and queues updates without a page-owned worker',async({page})=>{
 await page.goto('/tests/software-inventory.html');
 const section=page.getByRole('region',{name:'Agent software'});
 const toggle=section.getByRole('button',{name:/Agent software/});
 await expect(toggle).toHaveAttribute('aria-expanded','false');
 await expect(toggle).toContainText('2 updates');
 await toggle.click();
 await expect(section.getByText('Restart required')).toBeVisible();
 await expect(section.getByText('Inventory unavailable · SSH only')).toBeVisible();
 await expect(section.getByRole('button',{name:'Update',exact:true})).toHaveCount(1);
 const codex=section.locator('.software-entry').filter({hasText:'Codex'});
 await expect(codex.locator('.software-owner')).toHaveText('npm');
 expect((await codex.locator('summary').boundingBox())!.height).toBeLessThanOrEqual(32);
 await codex.locator('summary').click();
 await expect(codex.getByText(/Started with 1.8.0/)).toBeVisible();
 await codex.getByRole('button',{name:'Update',exact:true}).click();
 await expect(codex.getByText('Waiting for Codex sessions')).toBeVisible();
 await codex.getByRole('button',{name:'Cancel',exact:true}).click();
 await expect(codex.getByRole('button',{name:'Update',exact:true})).toBeVisible();
 await expect(page.locator('.resource-icon')).toHaveCount(4);
 expect(await page.locator('.machine-resource > span').first().evaluate(el=>getComputedStyle(el,'::before').content)).toBe('none');
 await section.getByRole('button',{name:'Update all',exact:true}).click();
 await expect(codex.getByText('Waiting for Codex sessions')).toBeVisible();
 await expect(section.getByRole('button',{name:'Update all',exact:true})).toBeDisabled();
 await page.screenshot({path:'test-results/software-dark.png'});
 await page.reload();await expect(toggle).toHaveAttribute('aria-expanded','false');
 await toggle.click();
 await page.evaluate(()=>document.documentElement.dataset.theme='light');
 await page.screenshot({path:'test-results/software-light.png'});
});
