import { cleanup, fireEvent, render, screen, waitFor } from "@solidjs/testing-library";
import { afterEach, expect, it, vi } from "vitest";
import { Composer } from "../src/App";
import * as uploads from "../src/uploads";
vi.mock("../src/uploads", async (original) => ({ ...await original<typeof import("../src/uploads")>(), hasNativePicker: () => true, pickNativeFiles: vi.fn(), transferFile: vi.fn() }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it("opens an upload choice with no project context and inserts a real local path", async () => {
  vi.mocked(uploads.pickNativeFiles).mockResolvedValue([{ name: "photo.png", localPath: "/Users/test/photo.png" }]);
  vi.mocked(uploads.transferFile).mockResolvedValue({ source: { name: "photo.png", localPath: "/Users/test/photo.png" }, path: "/Users/test/photo.png", destination: "local", connection: 0 });
  const send = vi.fn();
  render(() => <Composer placeholder="Task" busy={false} onSend={send} onStop={() => {}} uploadTarget="local" picker={false} />);
  fireEvent.click(screen.getByTitle("Add context"));
  fireEvent.click(screen.getByText("Upload file or image…"));
  await waitFor(() => expect((screen.getByPlaceholderText("Task") as HTMLTextAreaElement).value).toBe("@/Users/test/photo.png "));
  expect(uploads.transferFile).toHaveBeenCalledWith(expect.objectContaining({ name: "photo.png" }), "local");
  fireEvent.click(screen.getByTitle("Send"));
  await waitFor(() => expect(send).toHaveBeenCalledWith("@/Users/test/photo.png", []));
});
it("keeps the draft when transferring the file fails", async () => {
  vi.mocked(uploads.pickNativeFiles).mockResolvedValue([{ name: "photo.png", localPath: "/Users/test/photo.png" }]);
  vi.mocked(uploads.transferFile).mockRejectedValue(new Error("Machine offline"));
  render(() => <Composer placeholder="Task" busy={false} onSend={() => {}} onStop={() => {}} uploadTarget="ashur" picker={false} />);
  fireEvent.input(screen.getByPlaceholderText("Task"), { target: { value: "Keep my draft" } });
  fireEvent.click(screen.getByTitle("Add context")); fireEvent.click(screen.getByText("Upload file or image…"));
  await waitFor(() => expect(screen.getByRole("alert").textContent).toBe("Machine offline"));
  expect((screen.getByPlaceholderText("Task") as HTMLTextAreaElement).value).toBe("Keep my draft");
});
it("moves submitted text into a pending message immediately and restores it on rejection",async()=>{
 let finish!:(accepted:boolean)=>void;
 const send=vi.fn(()=>new Promise<boolean>(resolve=>{finish=resolve;}));
 render(()=><Composer placeholder="Task" busy={false} onSend={send} onStop={()=>{}}/>);
 const input=screen.getByPlaceholderText('Task') as HTMLTextAreaElement;
 fireEvent.input(input,{target:{value:'Please continue'}});
 fireEvent.click(screen.getByTitle('Send'));
 expect(input.value).toBe('');
 expect(input.readOnly).toBe(true);
 expect(screen.getByLabelText('Pending message').textContent).toContain('Please continue');
 fireEvent.keyDown(input,{key:'Enter'});
 await waitFor(()=>expect(send).toHaveBeenCalledTimes(1));
 finish(false);
 await waitFor(()=>expect(input.value).toBe('Please continue'));
 expect(screen.queryByLabelText('Pending message')).toBeNull();
 expect(input.readOnly).toBe(false);
});
it("removes the pending bubble once acknowledged and leaves the composer empty",async()=>{
 let finish!:(accepted:boolean)=>void;
 render(()=><Composer placeholder="Task" busy={false} onSend={()=>new Promise<boolean>(resolve=>{finish=resolve;})} onStop={()=>{}}/>);
 const input=screen.getByPlaceholderText('Task') as HTMLTextAreaElement;
 fireEvent.input(input,{target:{value:'Accepted message'}});
 fireEvent.keyDown(input,{key:'Enter'});
 await waitFor(()=>expect(finish).toBeDefined());
 finish(true);
 await waitFor(()=>expect(screen.queryByLabelText('Pending message')).toBeNull());
 expect(input.value).toBe('');
});
it("hands the optimistic message to the transcript immediately without a duplicate composer bubble", async () => {
  let finish!: (accepted: boolean) => void;
  const pending = vi.fn();
  const send = vi.fn(() => new Promise<boolean>(resolve => { finish = resolve; }));
  render(() => <Composer placeholder="Task" busy={false} onPending={pending} onSend={send} onStop={() => {}} />);
  const input = screen.getByPlaceholderText("Task") as HTMLTextAreaElement;
  fireEvent.input(input, { target: { value: "Optimistic turn" } });
  fireEvent.keyDown(input, { key: "Enter" });
  expect(pending).toHaveBeenCalledWith({ text: "Optimistic turn", images: [] });
  expect(screen.queryByLabelText("Pending message")).toBeNull();
  expect(input.value).toBe("");
  fireEvent.keyDown(input, { key: "Enter" });
  await waitFor(() => expect(send).toHaveBeenCalledTimes(1));
  finish(false);
  await waitFor(() => expect(input.value).toBe("Optimistic turn"));
  expect(pending).toHaveBeenLastCalledWith(null);
});
